#!/bin/sh -e
#
# SPDX-FileCopyrightText: 2024 Simon Holesch <simon@holesch.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

PS4=">>> "
set -x

editorconfig-checker
meson format --check-only
meson setup --werror --fatal-meson-warnings --reconfigure builddir-check
meson compile -C builddir-check
yamllint .clang-tidy
clang-tidy --verify-config
ninja -C builddir-check clang-tidy
ninja -C builddir-check clang-format-check
