#!/bin/sh -e
#
# SPDX-FileCopyrightText: 2025 Simon Holesch <simon@holesch.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# called by meson to get project version

main() {
    if [ "$1" = "--save" ]; then
        get_git_version > "${MESON_DIST_ROOT:?}/VERSION"
    elif [ -e VERSION ]; then
        cat VERSION
    else
        get_git_version
    fi
}

get_git_version() {
    version="$(git_describe)"
    version="${version#v}" # remove "v" prefix
    echo "$version"
}

git_describe() {
    if ! git -C "${MESON_SOURCE_ROOT:-$PWD}" describe --match "v*" --tags 2>/dev/null; then
        echo "v0.1.0-0-g$(git rev-parse --short HEAD)"
    fi
}

main "$@"
