# SPDX-FileCopyrightText: 2024 Simon Holesch <simon@holesch.de>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: on-push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        # The meson version in Ubuntu 24.04 doesn't support "meson format", yet.
        run: |
          pipx install \
            meson \
            ;
          wget 'https://github.com/editorconfig-checker/editorconfig-checker/releases/download/v3.2.0/ec-linux-amd64.tar.gz' -O - \
            | tar --gzip --extract --file - --directory /usr/local bin/ec-linux-amd64
          mv /usr/local/bin/ec-linux-amd64 /usr/local/bin/editorconfig-checker
          sudo apt-get update
          sudo apt-get install \
            libsodium-dev \
            libb2-dev \
            ninja-build \
            lcov \
            python3-pip \
            scdoc \
            wireguard-tools \
            ;
          pip install -r requirements.txt
      - name: Run static checks
        run: ./scripts/check
      - name: Lint with Ruff
        run: ruff check --output-format concise tests
      - name: Check format with Black
        run: black --check tests
      - name: Check import statement order with isort
        run: isort --check tests
      - name: Check REUSE compliance
        run: reuse lint
      - name: Build
        run: |
          meson setup --werror -Dtests=enabled -Ddocs=enabled builddir
          meson compile -C builddir
      - name: Test
        run: |
          meson test -C builddir --print-errorlogs
      - name: Build release
        run: |
          meson setup --werror -Dtests=disabled -Ddocs=disabled --buildtype=release builddir-release
          meson compile -C builddir-release
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            libb2-dev \
            libsodium-dev \
            meson \
            python3-pip \
            scdoc \
            wireguard-tools \
            ;
          pip install -r requirements.txt
      - name: Create tarball
        run: |
          meson setup --werror -Dtests=enabled -Ddocs=enabled builddir
          meson compile -C builddir
          meson dist -C builddir
      - name: Create release
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="$(./scripts/get_version)"
          gh release create \
            --title "${{ github.ref_name }}" \
            "${{ github.ref_name }}" \
            "builddir/meson-dist/salty-stun-$version.tar.xz"
